import type { Product } from './types';
import imagePlaceholders from './placeholder-images.json';

export const products: Product[] = [
  { code: 'AC', category: 'BEBIDA', description: 'ÁGUA COM GÁS', price: 3.5, active: true, imageUrl: imagePlaceholders.AC },
  { code: 'AS', category: 'BEBIDA', description: 'ÁGUA SEM GÁS', price: 3.0, active: true, imageUrl: imagePlaceholders.AS },
  { code: 'ÇA', category: 'BEBIDA', description: 'CAÇULA DE ABACAXI', price: 4.0, active: true, imageUrl: imagePlaceholders.ÇA },
  { code: 'ÇG', category: 'BEBIDA', description: 'CAÇULA DE GUARANÁ', price: 4.0, active: true, imageUrl: imagePlaceholders.ÇG },
  { code: 'ÇL', category: 'BEBIDA', description: 'CAÇULA DE LIMÃO', price: 4.0, active: true, imageUrl: imagePlaceholders.ÇL },
  { code: 'KS', category: 'BEBIDA', description: 'KS COCA COLA', price: 6.0, active: true, imageUrl: imagePlaceholders.KS },
  { code: 'FL', category: 'BEBIDA', description: 'KS FANTA LARANJA', price: 6.0, active: true, imageUrl: imagePlaceholders.FL },
  { code: 'FU', category: 'BEBIDA', description: 'KS FANTA UVA', price: 6.0, active: true, imageUrl: imagePlaceholders.FU },
  { code: 'SP', category: 'BEBIDA', description: 'KS SPRITE', price: 6.0, active: true, imageUrl: imagePlaceholders.SP },
  { code: 'CL', category: 'BEBIDA', description: 'LATA DE COCA COLA', price: 7.0, active: true, imageUrl: imagePlaceholders.CL },
  { code: 'CLZ', category: 'BEBIDA', description: 'LATA DE COCA COLA ZERO', price: 7.0, active: true, imageUrl: imagePlaceholders.CLZ },
  { code: 'SPL', category: 'BEBIDA', description: 'LATA DE SPRITE', price: 7.0, active: true, imageUrl: imagePlaceholders.SPL },
  { code: 'C1', category: 'BEBIDA', description: 'PET COCA COLA DE 1 LITRO', price: 10.0, active: true, imageUrl: imagePlaceholders.C1 },
  { code: 'PC', category: 'BEBIDA', description: 'PET MINI COCA COLA', price: 4.0, active: true, imageUrl: imagePlaceholders.PC },
  { code: 'PG', category: 'BEBIDA', description: 'PET MINI GUARANÁ', price: 4.0, active: true, imageUrl: imagePlaceholders.PG },
  { code: 'SL', category: 'BEBIDA', description: 'SUCO DE LARANJA', price: 10.0, active: true, imageUrl: imagePlaceholders.SL },
  { code: 'MS', category: 'MASSA', description: 'MASSA DE PASTEL PEMA', price: 10.0, active: true, imageUrl: imagePlaceholders.MS },
  { code: 'PM', category: 'MOLHO', description: 'MOLHO DE PIMENTA', price: 7.0, active: true, imageUrl: imagePlaceholders.PM },
  { code: 'BLC', category: 'SALGADO', description: 'BOLINHO DE CARNE', price: 11.0, active: true, imageUrl: imagePlaceholders.BLC },
  { code: 'BLO', category: 'SALGADO', description: 'BOLINHO DE OVO', price: 11.0, active: true, imageUrl: imagePlaceholders.BLO },
  { code: 'BLP', category: 'SALGADO', description: 'BOLINHO DE PRESUNTO E QUEIJO', price: 11.0, active: true, imageUrl: imagePlaceholders.BLP },
  { code: 'BLS', category: 'SALGADO', description: 'BOLINHO DE SALSICHA', price: 11.0, active: true, imageUrl: imagePlaceholders.BLS },
  { code: 'CX', category: 'SALGADO', description: 'COXINHA', price: 11.0, active: true, imageUrl: imagePlaceholders.CX },
  { code: 'E', category: 'SALGADO', description: 'ESPETO DE FRANGO', price: 11.0, active: true, imageUrl: imagePlaceholders.E },
  { code: 'KBC', category: 'SALGADO', description: 'KIBE COM QUEIJO', price: 11.0, active: true, imageUrl: imagePlaceholders.KBC },
  { code: 'KBS', category: 'SALGADO', description: 'KIBE SEM QUEIJO', price: 11.0, active: true, imageUrl: imagePlaceholders.KBS },
  { code: 'R', category: 'SALGADO', description: 'RISOLIS DE QUEIJO', price: 11.0, active: true, imageUrl: imagePlaceholders.R },
  { code: '4Q', category: 'GOURMET', description: '4 QUEIJOS', price: 18.0, active: true, imageUrl: imagePlaceholders['4Q'] },
  { code: 'COS', category: 'GOURMET', description: 'COSTELA COM MUSSARELA', price: 18.0, active: true, imageUrl: imagePlaceholders.COS },
  { code: 'TL', category: 'GOURMET', description: 'FILE DE TILAPIA', price: 18.0, active: true, imageUrl: imagePlaceholders.TL },
  { code: 'RJ', category: 'GOURMET', description: 'ROMEU E JULIETA', price: 15.0, active: true, imageUrl: imagePlaceholders.RJ },
  { code: 'B', category: 'GOURMET', description: 'BANANA, LEITE CONDENSADO E CANELA', price: 15.0, active: true, imageUrl: imagePlaceholders.B },
  { code: 'BGM', category: 'GOURMET', description: 'BRIGADEIRO COM MORANGO', price: 15.0, active: true, imageUrl: imagePlaceholders.BGM },
  { code: 'BG', category: 'GOURMET', description: 'BRIGADEIRO', price: 15.0, active: true, imageUrl: imagePlaceholders.BG },
  { code: 'V', category: 'PASTEL', description: 'VENTO', price: 7.0, active: true, imageUrl: imagePlaceholders.V },
  { code: 'Q', category: 'PASTEL', description: 'QUEIJO', price: 11.0, active: true, imageUrl: imagePlaceholders.Q },
  { code: 'CQ', category: 'PASTEL', description: 'CARNE COM QUEIJO', price: 11.0, active: true, imageUrl: imagePlaceholders.CQ },
  { code: 'KC', category: 'PASTEL', description: 'CALABRESA', price: 11.0, active: true, imageUrl: imagePlaceholders.KC },
  { code: 'FC', category: 'PASTEL', description: 'FRANGO COM REQUEIJAO', price: 11.0, active: true, imageUrl: imagePlaceholders.FC },
  { code: 'C', category: 'PASTEL', description: 'CARNE', price: 11.0, active: true, imageUrl: imagePlaceholders.C },
  { code: 'P', category: 'PASTEL', description: 'PIZZA', price: 11.0, active: true, imageUrl: imagePlaceholders.P },
  { code: 'PN', category: 'PASTEL', description: 'PALMITO NORMAL', price: 11.0, active: true, imageUrl: imagePlaceholders.PN },
  { code: 'PP', category: 'PASTEL', description: 'PALMITO PICANTE', price: 11.0, active: true, imageUrl: imagePlaceholders.PP },
  { code: 'CS', category: 'PASTEL', description: 'CARNE SECA', price: 11.0, active: true, imageUrl: imagePlaceholders.CS },
  { code: 'BR', category: 'PASTEL', description: 'BROCOLIS', price: 11.0, active: true, imageUrl: imagePlaceholders.BR },
  { code: 'CS/Q', category: '21CM', description: 'CARNE SECA COM QUEIJO', price: 14.0, active: true, imageUrl: imagePlaceholders['CS/Q'] },
  { code: 'Q/M', category: '21CM', description: 'Queijo com Mussarela (21cm)', price: 14.0, active: true, imageUrl: imagePlaceholders['Q/M'] },
  { code: 'K/M/Q/P/T/BR/30', category: '30CM', description: 'Calabresa, Mussarela, Queijo, Pizza, Tomate, Brócolis (30cm)', price: 27.0, active: true, imageUrl: imagePlaceholders['K/M/Q/P/T/BR/30'] },
  { code: 'FC/Q', category: '21CM', description: 'Frango com Requeijão e Queijo (21cm)', price: 14.0, active: true, imageUrl: imagePlaceholders['FC/Q'] },
  { code: 'P/C/F/M/PN/K/30', category: '30CM', description: 'Pizza, Carne, Frango, Mussarela, Palmito, Calabresa (30cm)', price: 27.0, active: true, imageUrl: imagePlaceholders['P/C/F/M/PN/K/30'] },
  { code: 'Q/PP', category: '21CM', description: 'Queijo com Palmito Picante (21cm)', price: 14.0, active: true, imageUrl: imagePlaceholders['Q/PP'] },
  { code: 'BR/CR', category: '21CM', description: 'Brócolis com Requeijão (21cm)', price: 14.0, active: true, imageUrl: imagePlaceholders['BR/CR'] },
  { code: 'CS/CAT', category: '21CM', description: 'CARNE SECA COM REQUEIJAO', price: 14.0, active: true, imageUrl: imagePlaceholders['CS/CAT'] },
  { code: 'CQ/O', category: '21CM', description: 'Carne com Queijo e Ovo (21cm)', price: 14.0, active: true, imageUrl: imagePlaceholders['CQ/O'] },
  { code: 'P/CAT', category: '21CM', description: 'Pizza com Requeijão (21cm)', price: 14.0, active: true, imageUrl: imagePlaceholders['P/CAT'] },
  { code: 'BR/BC/PP/Q/CS/P/30', category: '30CM', description: 'Brócolis, Bacon, Palmito Picante, Queijo, Carne Seca, Pizza (30cm)', price: 27.0, active: true, imageUrl: imagePlaceholders['BR/BC/PP/Q/CS/P/30'] },
  { code: 'BR/CAT', category: '21CM', description: 'Brócolis com Requeijão (21cm)', price: 14.0, active: true, imageUrl: imagePlaceholders['BR/CAT'] },
  { code: 'PN/M', category: '21CM', description: 'Palmito com Mussarela (21cm)', price: 14.0, active: true, imageUrl: imagePlaceholders['PN/M'] },
  { code: 'CQ/C/Q', category: '21CM', description: 'Carne com Queijo (Duplo) (21cm)', price: 19.0, active: true, imageUrl: imagePlaceholders['CQ/C/Q'] },
  { code: 'K/Q', category: '21CM', description: 'Calabresa com Queijo (21cm)', price: 14.0, active: true, imageUrl: imagePlaceholders['K/Q'] },
  { code: 'Q/P/C/O/25', category: '25CM', description: 'Queijo, Pizza, Carne, Ovo (25cm)', price: 22.0, active: true, imageUrl: imagePlaceholders['Q/P/C/O/25'] },
  { code: 'KC/Q', category: '21CM', description: 'Calabresa com Queijo (21cm)', price: 14.0, active: true, imageUrl: imagePlaceholders['KC/Q'] },
  { code: 'BR/BC/Q', category: '21CM', description: 'Brócolis, Bacon, Queijo (21cm)', price: 19.0, active: true, imageUrl: imagePlaceholders['BR/BC/Q'] },
  { code: 'KC/BC/C/P/CAT/BC/30', category: '30CM', description: 'Calabresa, Bacon, Carne, Pizza, Requeijão (30cm)', price: 27.0, active: true, imageUrl: imagePlaceholders['KC/BC/C/P/CAT/BC/30'] },
  { code: 'FC/PN', category: '21CM', description: 'Frango com Requeijão e Palmito (21cm)', price: 14.0, active: true, imageUrl: imagePlaceholders['FC/PN'] },
  { code: 'KC/C', category: '21CM', description: 'Calabresa com Carne (21cm)', price: 14.0, active: true, imageUrl: imagePlaceholders['KC/C'] },
  { code: 'CQ/CR/O/Q/25', category: '25CM', description: 'Carne, Queijo, Requeijão, Ovo (25cm)', price: 22.0, active: true, imageUrl: imagePlaceholders['CQ/CR/O/Q/25'] },
  { code: 'CQ/T/CR/Q/25', category: '25CM', description: 'Carne, Queijo, Tomate, Requeijão (25cm)', price: 22.0, active: true, imageUrl: imagePlaceholders['CQ/T/CR/Q/25'] },
  { code: 'CQ/BC/PN/CR/25', category: '25CM', description: 'Carne, Queijo, Bacon, Palmito, Requeijão (25cm)', price: 22.0, active: true, imageUrl: imagePlaceholders['CQ/BC/PN/CR/25'] },
  { code: 'Q/BR', category: '21CM', description: 'Queijo com Brócolis (21cm)', price: 14.0, active: true, imageUrl: imagePlaceholders['Q/BR'] },
  { code: 'Q/BC', category: '21CM', description: 'Queijo com Bacon (21cm)', price: 14.0, active: true, imageUrl: imagePlaceholders['Q/BC'] },
  { code: 'PP/CS', category: '21CM', description: 'Palmito Picante com Carne Seca (21cm)', price: 14.0, active: true, imageUrl: imagePlaceholders['PP/CS'] },
  { code: 'P/BR/K/CAT/25', category: '25CM', description: 'Pizza, Brócolis, Calabresa, Requeijão (25cm)', price: 22.0, active: true, imageUrl: imagePlaceholders['P/BR/K/CAT/25'] },
  { code: 'KC/BR', category: '21CM', description: 'Calabresa com Brócolis (21cm)', price: 14.0, active: true, imageUrl: imagePlaceholders['KC/BR'] },
  { code: 'Q/CAT', category: '21CM', description: 'Queijo com Requeijão (21cm)', price: 14.0, active: true, imageUrl: imagePlaceholders['Q/CAT'] },
  { code: 'Q/P/PP/CR/C/K/30', category: '30CM', description: 'Queijo, Pizza, Palmito Picante, Requeijão, Carne, Calabresa (30cm)', price: 27.0, active: true, imageUrl: imagePlaceholders['Q/P/PP/CR/C/K/30'] },
  { code: 'CQ/BC/CAT/CS/CR/Q/30', category: '30CM', description: 'Carne, Queijo, Bacon, Requeijão, Carne Seca (30cm)', price: 27.0, active: true, imageUrl: imagePlaceholders['CQ/BC/CAT/CS/CR/Q/30'] },
  { code: 'K', category: '21CM', description: 'SÓ CALABRESA', price: 11.0, active: true, imageUrl: imagePlaceholders.K },
  { code: 'FC/K/CAT/F/25', category: '25CM', description: 'Frango, Calabresa, Requeijão (25cm)', price: 22.0, active: true, imageUrl: imagePlaceholders['FC/K/CAT/F/25'] },
  { code: 'PP/BR', category: '21CM', description: 'Palmito Picante com Brócolis (21cm)', price: 14.0, active: true, imageUrl: imagePlaceholders['PP/BR'] },
  { code: 'PN/Q', category: '21CM', description: 'Palmito com Queijo (21cm)', price: 14.0, active: true, imageUrl: imagePlaceholders['PN/Q'] },
  { code: 'CQ/F/M/K/Q/BC/30', category: '30CM', description: 'Carne, Queijo, Frango, Mussarela, Calabresa, Bacon (30cm)', price: 27.0, active: true, imageUrl: imagePlaceholders['CQ/F/M/K/Q/BC/30'] },
  { code: 'FC/F/Q/Q/F/F/30', category: '30CM', description: 'Frango com Requeijão (Triplo) e Queijo (Duplo) (30cm)', price: 27.0, active: true, imageUrl: imagePlaceholders['FC/F/Q/Q/F/F/30'] },
  { code: 'FC/BR/CS/CR/PN/Q/30', category: '30CM', description: 'Frango, Brócolis, Carne Seca, Requeijão, Palmito, Queijo (30cm)', price: 27.0, active: true, imageUrl: imagePlaceholders['FC/BR/CS/CR/PN/Q/30'] },
  { code: 'KC/Q/PN/CS/25', category: '25CM', description: 'Calabresa, Queijo, Palmito, Carne Seca (25cm)', price: 22.0, active: true, imageUrl: imagePlaceholders['KC/Q/PN/CS/25'] },
  { code: 'FC/BC/BR/M/T/K/30', category: '30CM', description: 'Frango, Bacon, Brócolis, Mussarela, Tomate, Calabresa (30cm)', price: 27.0, active: true, imageUrl: imagePlaceholders['FC/BC/BR/M/T/K/30'] },
  { code: 'CQ/BC/CR/PP/25', category: '25CM', description: 'Carne, Queijo, Bacon, Requeijão, Palmito Picante (25cm)', price: 22.0, active: true, imageUrl: imagePlaceholders['CQ/BC/CR/PP/25'] },
  { code: 'CS/Q/T/PP/25', category: '25CM', description: 'Carne Seca, Queijo, Tomate, Palmito Picante (25cm)', price: 22.0, active: true, imageUrl: imagePlaceholders['CS/Q/T/PP/25'] },
  { code: 'KC/P/F/CR/PP/K/30', category: '30CM', description: 'Calabresa, Pizza, Frango, Requeijão, Palmito Picante (30cm)', price: 27.0, active: true, imageUrl: imagePlaceholders['KC/P/F/CR/PP/K/30'] },
  { code: 'K/BC/T/C/K/Q/30', category: '30CM', description: 'Calabresa, Bacon, Tomate, Carne, Queijo (30cm)', price: 27.0, active: true, imageUrl: imagePlaceholders['K/BC/T/C/K/Q/30'] },
  { code: 'FC/BC/Q/T/25', category: '25CM', description: 'Frango com Requeijão, Bacon, Queijo, Tomate (25cm)', price: 22.0, active: true, imageUrl: imagePlaceholders['FC/BC/Q/T/25'] },
  { code: 'CQ/BC/CS/CR/K/Q/30', category: '30CM', description: 'Carne, Queijo, Bacon, Carne Seca, Requeijão, Calabresa (30cm)', price: 27.0, active: true, imageUrl: imagePlaceholders['CQ/BC/CS/CR/K/Q/30'] },
  { code: 'FC/Q/F/Q/25', category: '25CM', description: 'Frango com Requeijão (Duplo) e Queijo (Duplo) (25cm)', price: 22.0, active: true, imageUrl: imagePlaceholders['FC/Q/F/Q/25'] },
  { code: 'Q/CS/CR/Q/25', category: '25CM', description: 'Queijo, Carne Seca, Requeijão (25cm)', price: 22.0, active: true, imageUrl: imagePlaceholders['Q/CS/CR/Q/25'] },
  { code: 'Q/T', category: '21CM', description: 'Queijo com Tomate (21cm)', price: 14.0, active: true, imageUrl: imagePlaceholders['Q/T'] },
  { code: 'CQ/PN', category: '21CM', description: 'Carne com Queijo e Palmito (21cm)', price: 14.0, active: true, imageUrl: imagePlaceholders['CQ/PN'] },
  { code: 'CQ/O/BC/CR/25', category: '25CM', description: 'Carne, Queijo, Ovo, Bacon, Requeijão (25cm)', price: 22.0, active: true, imageUrl: imagePlaceholders['CQ/O/BC/CR/25'] },
  { code: 'Q/P/BC/CAT/25', category: '25CM', description: 'Queijo, Pizza, Bacon, Requeijão (25cm)', price: 22.0, active: true, imageUrl: imagePlaceholders['Q/P/BC/CAT/25'] },
  { code: 'CQ/BC/K/CAT/25', category: '25CM', description: 'Carne, Queijo, Bacon, Calabresa, Requeijão (25cm)', price: 22.0, active: true, imageUrl: imagePlaceholders['CQ/BC/K/CAT/25'] },
  { code: 'COS/BC/BR/K/O/Q/30', category: '30CM', description: 'Costela, Bacon, Brócolis, Calabresa, Ovo, Queijo (30cm)', price: 27.0, active: true, imageUrl: imagePlaceholders['COS/BC/BR/K/O/Q/30'] },
  { code: 'C/BR', category: '21CM', description: 'Carne com Brócolis (21cm)', price: 14.0, active: true, imageUrl: imagePlaceholders['C/BR'] },
  { code: 'CS/CR', category: '21CM', description: 'Carne Seca com Requeijão (21cm)', price: 14.0, active: true, imageUrl: imagePlaceholders['CS/CR'] },
];
